"""Built-in reference data used to seed a fresh database.

IMPORTANT
---------
Everything in this file is an *editable default*, not a fact claim:

* Source/account classifications are starting points for the verification
  engine and can be changed on the Settings page at any time.
* The fighter list exists so the app can *recognise names in text*. It holds
  no statistics, records, rankings or divisions - those are only ever written
  from data the collectors actually fetch.
* Feed URLs are the publicly documented RSS endpoints for each outlet. Each
  source may list fallback URLs; the collector records which one worked, and
  the Source Health page shows any that fail.
"""
from __future__ import annotations

from typing import Any, Dict, List

from models.types import SourceType

# --------------------------------------------------------------- sources ---
# adapter: "rss" | "ufc_rankings" | "ufc_events"
BUILTIN_SOURCES: List[Dict[str, Any]] = [
    {
        "key": "ufc_com",
        "name": "UFC.com",
        "adapter": "rss",
        "feed_url": "https://www.ufc.com/rss/news",
        "fallback_urls": ["https://www.ufc.com/rss/news/all", "https://www.ufc.com/feed"],
        "homepage": "https://www.ufc.com/news",
        "domain": "ufc.com",
        "source_type": SourceType.OFFICIAL.value,
        "reliability_weight": 1.0,
        "independence_group": "ufc_official",
        "priority": 1,
        "enabled": 1,
        "notes": "Official UFC newsroom. Treated as official confirmation.",
    },
    {
        "key": "ufc_rankings",
        "name": "UFC.com Rankings",
        "adapter": "ufc_rankings",
        "feed_url": "https://www.ufc.com/rankings",
        "fallback_urls": [],
        "homepage": "https://www.ufc.com/rankings",
        "domain": "ufc.com",
        "source_type": SourceType.OFFICIAL.value,
        "reliability_weight": 1.0,
        "independence_group": "ufc_official",
        "priority": 2,
        "enabled": 1,
        "notes": "Official rankings page. The published ranking system/version is stored with every snapshot.",
    },
    {
        "key": "ufc_events",
        "name": "UFC.com Events",
        "adapter": "ufc_events",
        "feed_url": "https://www.ufc.com/events",
        "fallback_urls": [],
        "homepage": "https://www.ufc.com/events",
        "domain": "ufc.com",
        "source_type": SourceType.OFFICIAL.value,
        "reliability_weight": 1.0,
        "independence_group": "ufc_official",
        "priority": 3,
        "enabled": 1,
        "notes": "Official event schedule (names, dates, locations).",
    },
    {
        "key": "espn_mma",
        "name": "ESPN MMA",
        "adapter": "rss",
        "feed_url": "https://www.espn.com/espn/rss/mma/news",
        "fallback_urls": ["https://www.espn.com/espn/rss/news"],
        "homepage": "https://www.espn.com/mma/",
        "domain": "espn.com",
        "source_type": SourceType.MAJOR_NEWS.value,
        "reliability_weight": 0.9,
        "independence_group": "espn",
        "priority": 10,
        "enabled": 1,
        "notes": "",
    },
    {
        "key": "mma_fighting",
        "name": "MMA Fighting",
        "adapter": "rss",
        "feed_url": "https://www.mmafighting.com/rss/current",
        "fallback_urls": ["https://www.mmafighting.com/rss/current.xml"],
        "homepage": "https://www.mmafighting.com/",
        "domain": "mmafighting.com",
        "source_type": SourceType.MAJOR_NEWS.value,
        "reliability_weight": 0.88,
        "independence_group": "vox_sbnation",
        "priority": 11,
        "enabled": 1,
        "notes": "Shares ownership with MMA Mania - the two do not count as independent of each other.",
    },
    {
        "key": "mma_junkie",
        "name": "MMA Junkie",
        "adapter": "rss",
        "feed_url": "https://mmajunkie.usatoday.com/feed",
        "fallback_urls": ["https://mmajunkie.usatoday.com/feed/", "https://mmajunkie.com/feed"],
        "homepage": "https://mmajunkie.usatoday.com/",
        "domain": "mmajunkie.usatoday.com",
        "source_type": SourceType.MAJOR_NEWS.value,
        "reliability_weight": 0.85,
        "independence_group": "usatoday",
        "priority": 12,
        "enabled": 1,
        "notes": "",
    },
    {
        "key": "sherdog",
        "name": "Sherdog",
        "adapter": "rss",
        "feed_url": "https://www.sherdog.com/rss/news.xml",
        "fallback_urls": ["https://www.sherdog.com/rss/news"],
        "homepage": "https://www.sherdog.com/news/",
        "domain": "sherdog.com",
        "source_type": SourceType.MAJOR_NEWS.value,
        "reliability_weight": 0.8,
        "independence_group": "sherdog",
        "priority": 13,
        "enabled": 1,
        "notes": "",
    },
    {
        "key": "google_news_ufc",
        "name": "Google News (UFC)",
        "adapter": "rss",
        "feed_url": "https://news.google.com/rss/search?q=UFC+OR+%22mixed+martial+arts%22+when:2d&hl=en-US&gl=US&ceid=US:en",
        "fallback_urls": ["https://news.google.com/rss/search?q=UFC&hl=en-US&gl=US&ceid=US:en"],
        "homepage": "https://news.google.com/",
        "domain": "news.google.com",
        "source_type": SourceType.UNKNOWN.value,
        "reliability_weight": 0.5,
        "independence_group": "aggregator",
        "priority": 20,
        "enabled": 1,
        "notes": "Aggregator: each item is re-classified using the publisher it links to, so it never inflates source counts.",
    },
    {
        "key": "google_news_ufc_rumors",
        "name": "Google News (UFC rumors & reports)",
        "adapter": "rss",
        "feed_url": "https://news.google.com/rss/search?q=UFC+(rumor+OR+report+OR+injury+OR+replacement+OR+cancelled)+when:2d&hl=en-US&gl=US&ceid=US:en",
        "fallback_urls": [],
        "homepage": "https://news.google.com/",
        "domain": "news.google.com",
        "source_type": SourceType.UNKNOWN.value,
        "reliability_weight": 0.45,
        "independence_group": "aggregator",
        "priority": 21,
        "enabled": 1,
        "notes": "Discovery feed for developing/rumored items. Low weight on purpose.",
    },
    {
        "key": "mma_mania",
        "name": "MMA Mania",
        "adapter": "rss",
        "feed_url": "https://www.mmamania.com/rss/current",
        "fallback_urls": [],
        "homepage": "https://www.mmamania.com/",
        "domain": "mmamania.com",
        "source_type": SourceType.TRUSTED_REPORTER.value,
        "reliability_weight": 0.6,
        "independence_group": "vox_sbnation",
        "priority": 30,
        "enabled": 1,
        "notes": "Same publisher family as MMA Fighting.",
    },
    {
        "key": "bloody_elbow",
        "name": "Bloody Elbow",
        "adapter": "rss",
        "feed_url": "https://bloodyelbow.com/feed/",
        "fallback_urls": ["https://www.bloodyelbow.com/rss/current"],
        "homepage": "https://bloodyelbow.com/",
        "domain": "bloodyelbow.com",
        "source_type": SourceType.TRUSTED_REPORTER.value,
        "reliability_weight": 0.65,
        "independence_group": "bloodyelbow",
        "priority": 31,
        "enabled": 1,
        "notes": "",
    },
    {
        "key": "fightful",
        "name": "Fightful",
        "adapter": "rss",
        "feed_url": "https://www.fightful.com/rss.xml",
        "fallback_urls": ["https://www.fightful.com/feed"],
        "homepage": "https://www.fightful.com/mma",
        "domain": "fightful.com",
        "source_type": SourceType.TRUSTED_REPORTER.value,
        "reliability_weight": 0.6,
        "independence_group": "fightful",
        "priority": 32,
        "enabled": 1,
        "notes": "",
    },
    {
        "key": "bjpenn_com",
        "name": "BJPenn.com",
        "adapter": "rss",
        "feed_url": "https://www.bjpenn.com/feed/",
        "fallback_urls": [],
        "homepage": "https://www.bjpenn.com/",
        "domain": "bjpenn.com",
        "source_type": SourceType.UNKNOWN.value,
        "reliability_weight": 0.4,
        "independence_group": "bjpenn",
        "priority": 40,
        "enabled": 1,
        "notes": "Frequently aggregates other outlets - useful for discovery, weak as confirmation.",
    },
    {
        "key": "lowkick_mma",
        "name": "LowKick MMA",
        "adapter": "rss",
        "feed_url": "https://www.lowkickmma.com/feed/",
        "fallback_urls": [],
        "homepage": "https://www.lowkickmma.com/",
        "domain": "lowkickmma.com",
        "source_type": SourceType.UNKNOWN.value,
        "reliability_weight": 0.35,
        "independence_group": "lowkick",
        "priority": 41,
        "enabled": 1,
        "notes": "Rumor-heavy. Never counted as confirmation.",
    },
    {
        "key": "the_mac_life",
        "name": "The Mac Life",
        "adapter": "rss",
        "feed_url": "https://themaclife.com/feed/",
        "fallback_urls": [],
        "homepage": "https://themaclife.com/",
        "domain": "themaclife.com",
        "source_type": SourceType.UNKNOWN.value,
        "reliability_weight": 0.4,
        "independence_group": "maclife",
        "priority": 42,
        "enabled": 0,
        "notes": "Disabled by default - enable on the Settings page if you want it.",
    },
    {
        "key": "reddit_mma",
        "name": "Reddit r/MMA",
        "adapter": "rss",
        "feed_url": "https://www.reddit.com/r/MMA/hot/.rss",
        "fallback_urls": ["https://www.reddit.com/r/MMA/.rss"],
        "homepage": "https://www.reddit.com/r/MMA/",
        "domain": "reddit.com",
        "source_type": SourceType.FAN_ACCOUNT.value,
        "reliability_weight": 0.15,
        "independence_group": "reddit",
        "priority": 50,
        "enabled": 0,
        "notes": "Discovery/trending signal only. Disabled by default; never counts as confirmation.",
    },
]

# ------------------------------------------------- source classifications --
# kind: domain | author | x_account
DOMAIN_CLASSIFICATIONS: List[Dict[str, Any]] = [
    ("ufc.com", "UFC.com", SourceType.OFFICIAL.value, 1.0, "ufc_official"),
    ("espn.com", "ESPN", SourceType.MAJOR_NEWS.value, 0.9, "espn"),
    ("espn.co.uk", "ESPN UK", SourceType.MAJOR_NEWS.value, 0.85, "espn"),
    ("mmafighting.com", "MMA Fighting", SourceType.MAJOR_NEWS.value, 0.88, "vox_sbnation"),
    ("mmajunkie.usatoday.com", "MMA Junkie", SourceType.MAJOR_NEWS.value, 0.85, "usatoday"),
    ("mmajunkie.com", "MMA Junkie", SourceType.MAJOR_NEWS.value, 0.85, "usatoday"),
    ("usatoday.com", "USA Today", SourceType.MAJOR_NEWS.value, 0.8, "usatoday"),
    ("sherdog.com", "Sherdog", SourceType.MAJOR_NEWS.value, 0.8, "sherdog"),
    ("mmamania.com", "MMA Mania", SourceType.TRUSTED_REPORTER.value, 0.6, "vox_sbnation"),
    ("bloodyelbow.com", "Bloody Elbow", SourceType.TRUSTED_REPORTER.value, 0.65, "bloodyelbow"),
    ("fightful.com", "Fightful", SourceType.TRUSTED_REPORTER.value, 0.6, "fightful"),
    ("cagesidepress.com", "Cageside Press", SourceType.TRUSTED_REPORTER.value, 0.55, "cagesidepress"),
    ("mmanews.com", "MMA News", SourceType.UNKNOWN.value, 0.4, "mmanews"),
    ("bjpenn.com", "BJPenn.com", SourceType.UNKNOWN.value, 0.4, "bjpenn"),
    ("lowkickmma.com", "LowKick MMA", SourceType.UNKNOWN.value, 0.35, "lowkick"),
    ("themaclife.com", "The Mac Life", SourceType.UNKNOWN.value, 0.4, "maclife"),
    ("sports.yahoo.com", "Yahoo Sports", SourceType.MAJOR_NEWS.value, 0.75, "yahoo"),
    ("si.com", "Sports Illustrated", SourceType.MAJOR_NEWS.value, 0.75, "si"),
    ("foxsports.com", "FOX Sports", SourceType.MAJOR_NEWS.value, 0.75, "fox"),
    ("cbssports.com", "CBS Sports", SourceType.MAJOR_NEWS.value, 0.75, "cbs"),
    ("bleacherreport.com", "Bleacher Report", SourceType.TRUSTED_REPORTER.value, 0.6, "br"),
    ("theathletic.com", "The Athletic", SourceType.MAJOR_NEWS.value, 0.85, "nyt"),
    ("nytimes.com", "The New York Times", SourceType.MAJOR_NEWS.value, 0.85, "nyt"),
    ("bbc.com", "BBC Sport", SourceType.MAJOR_NEWS.value, 0.85, "bbc"),
    ("bbc.co.uk", "BBC Sport", SourceType.MAJOR_NEWS.value, 0.85, "bbc"),
    ("talksport.com", "talkSPORT", SourceType.UNKNOWN.value, 0.45, "talksport"),
    ("dailymail.co.uk", "Daily Mail", SourceType.UNKNOWN.value, 0.3, "dailymail"),
    ("thesun.co.uk", "The Sun", SourceType.UNKNOWN.value, 0.25, "thesun"),
    ("mirror.co.uk", "The Mirror", SourceType.UNKNOWN.value, 0.3, "reach"),
    ("express.co.uk", "Daily Express", SourceType.UNKNOWN.value, 0.3, "reach"),
    ("sportskeeda.com", "Sportskeeda", SourceType.FAN_ACCOUNT.value, 0.2, "sportskeeda"),
    ("essentiallysports.com", "EssentiallySports", SourceType.FAN_ACCOUNT.value, 0.2, "essentially"),
    ("givemesport.com", "GiveMeSport", SourceType.FAN_ACCOUNT.value, 0.25, "gms"),
    ("msn.com", "MSN (syndicated)", SourceType.UNKNOWN.value, 0.3, "aggregator"),
    ("news.google.com", "Google News (aggregator)", SourceType.UNKNOWN.value, 0.3, "aggregator"),
    ("reddit.com", "Reddit", SourceType.FAN_ACCOUNT.value, 0.15, "reddit"),
    ("youtube.com", "YouTube", SourceType.UNKNOWN.value, 0.3, "youtube"),
]

# Bylines that identify an outlet-affiliated reporter. Editable defaults - the
# app uses them to decide how much weight a single report carries, nothing else.
AUTHOR_CLASSIFICATIONS: List[Dict[str, Any]] = [
    ("Ariel Helwani", SourceType.ESTABLISHED_JOURNALIST.value, 0.85),
    ("Brett Okamoto", SourceType.ESTABLISHED_JOURNALIST.value, 0.85),
    ("Marc Raimondi", SourceType.ESTABLISHED_JOURNALIST.value, 0.8),
    ("Jeff Wagenheim", SourceType.ESTABLISHED_JOURNALIST.value, 0.8),
    ("Shaheen Al-Shatti", SourceType.ESTABLISHED_JOURNALIST.value, 0.8),
    ("Damon Martin", SourceType.ESTABLISHED_JOURNALIST.value, 0.78),
    ("Mike Heck", SourceType.ESTABLISHED_JOURNALIST.value, 0.75),
    ("Alexander K. Lee", SourceType.ESTABLISHED_JOURNALIST.value, 0.75),
    ("Guilherme Cruz", SourceType.ESTABLISHED_JOURNALIST.value, 0.75),
    ("E. Casey Leydon", SourceType.TRUSTED_REPORTER.value, 0.7),
    ("Nolan King", SourceType.ESTABLISHED_JOURNALIST.value, 0.78),
    ("Mike Bohn", SourceType.ESTABLISHED_JOURNALIST.value, 0.78),
    ("Farah Hannoun", SourceType.TRUSTED_REPORTER.value, 0.72),
    ("Simon Samano", SourceType.TRUSTED_REPORTER.value, 0.7),
    ("Danny Segura", SourceType.TRUSTED_REPORTER.value, 0.7),
    ("John Morgan", SourceType.ESTABLISHED_JOURNALIST.value, 0.78),
    ("Tristen Critchfield", SourceType.TRUSTED_REPORTER.value, 0.7),
    ("Mike Sloan", SourceType.TRUSTED_REPORTER.value, 0.65),
]

# ----------------------------------------------- monitored X/Twitter accounts
# Seeded as *suggestions*. Nothing is fetched unless X_BEARER_TOKEN is set, and
# every row can be edited or removed on the Settings page.
MONITORED_X_ACCOUNTS: List[Dict[str, Any]] = [
    {"username": "ufc", "display_name": "UFC", "account_type": SourceType.OFFICIAL.value,
     "category": "official", "priority": 1},
    {"username": "danawhite", "display_name": "Dana White", "account_type": SourceType.OFFICIAL.value,
     "category": "official", "priority": 2},
    {"username": "ufcnews", "display_name": "UFC News", "account_type": SourceType.OFFICIAL.value,
     "category": "official", "priority": 3},
    {"username": "espnmma", "display_name": "ESPN MMA", "account_type": SourceType.MAJOR_NEWS.value,
     "category": "reporter", "priority": 10},
    {"username": "mmafighting", "display_name": "MMA Fighting", "account_type": SourceType.MAJOR_NEWS.value,
     "category": "reporter", "priority": 11},
    {"username": "mmajunkie", "display_name": "MMA Junkie", "account_type": SourceType.MAJOR_NEWS.value,
     "category": "reporter", "priority": 12},
    {"username": "sherdogdotcom", "display_name": "Sherdog", "account_type": SourceType.MAJOR_NEWS.value,
     "category": "reporter", "priority": 13},
    {"username": "arielhelwani", "display_name": "Ariel Helwani",
     "account_type": SourceType.ESTABLISHED_JOURNALIST.value, "category": "journalist", "priority": 5},
    {"username": "bokamotoespn", "display_name": "Brett Okamoto",
     "account_type": SourceType.ESTABLISHED_JOURNALIST.value, "category": "journalist", "priority": 6},
    {"username": "marc_raimondi", "display_name": "Marc Raimondi",
     "account_type": SourceType.ESTABLISHED_JOURNALIST.value, "category": "journalist", "priority": 7},
    {"username": "damonmartin", "display_name": "Damon Martin",
     "account_type": SourceType.ESTABLISHED_JOURNALIST.value, "category": "journalist", "priority": 8},
    {"username": "mikeheck_jr", "display_name": "Mike Heck",
     "account_type": SourceType.ESTABLISHED_JOURNALIST.value, "category": "journalist", "priority": 9},
    {"username": "johnmorgan_mma", "display_name": "John Morgan",
     "account_type": SourceType.ESTABLISHED_JOURNALIST.value, "category": "journalist", "priority": 14},
    {"username": "nolanking", "display_name": "Nolan King",
     "account_type": SourceType.TRUSTED_REPORTER.value, "category": "reporter", "priority": 15},
    {"username": "mikebohnmma", "display_name": "Mike Bohn",
     "account_type": SourceType.TRUSTED_REPORTER.value, "category": "reporter", "priority": 16},
    {"username": "jonnybones", "display_name": "Jon Jones", "account_type": SourceType.FIGHTER.value,
     "category": "fighter", "priority": 20},
    {"username": "alexpoatanpereira", "display_name": "Alex Pereira",
     "account_type": SourceType.FIGHTER.value, "category": "fighter", "priority": 21},
    {"username": "makhachevmma", "display_name": "Islam Makhachev",
     "account_type": SourceType.FIGHTER.value, "category": "fighter", "priority": 22},
    {"username": "asaspinall", "display_name": "Tom Aspinall", "account_type": SourceType.FIGHTER.value,
     "category": "fighter", "priority": 23},
    {"username": "ufcchito", "display_name": "Ilia Topuria", "account_type": SourceType.FIGHTER.value,
     "category": "fighter", "priority": 24},
    {"username": "sean_omalley", "display_name": "Sean O'Malley", "account_type": SourceType.FIGHTER.value,
     "category": "fighter", "priority": 25},
    {"username": "alexvolkanovski", "display_name": "Alexander Volkanovski",
     "account_type": SourceType.FIGHTER.value, "category": "fighter", "priority": 26},
    {"username": "teamkhabib", "display_name": "Khabib Nurmagomedov",
     "account_type": SourceType.COACH_TEAM.value, "category": "coach_team", "priority": 30},
    {"username": "javier_mendez", "display_name": "Javier Mendez (AKA)",
     "account_type": SourceType.COACH_TEAM.value, "category": "coach_team", "priority": 31},
    {"username": "coach_kavanagh", "display_name": "John Kavanagh (SBG)",
     "account_type": SourceType.COACH_TEAM.value, "category": "coach_team", "priority": 32},
    {"username": "aliabdelaziz00", "display_name": "Ali Abdelaziz (Dominance MMA)",
     "account_type": SourceType.PROMOTER.value, "category": "promoter", "priority": 35},
]

# --------------------------------------------------- fighter name registry --
# Names only - used to recognise who a story is about. No records, no stats,
# no rankings: those are written only from collected data.
# Format: (display name, nickname or "", [aliases])
FIGHTER_NAMES: List[tuple] = [
    ("Jon Jones", "Bones", ["Jonny Bones"]),
    ("Tom Aspinall", "", []),
    ("Ciryl Gane", "Bon Gamin", []),
    ("Stipe Miocic", "", []),
    ("Sergei Pavlovich", "", []),
    ("Curtis Blaydes", "Razor", []),
    ("Alexander Volkov", "Drago", []),
    ("Jailton Almeida", "Malhadinho", []),
    ("Derrick Lewis", "The Black Beast", []),
    ("Alex Pereira", "Poatan", ["Alex Poatan"]),
    ("Magomed Ankalaev", "", []),
    ("Jiri Prochazka", "Denisa", ["Jiri Prochazka"]),
    ("Jamahal Hill", "Sweet Dreams", []),
    ("Carlos Ulberg", "Black Jag", []),
    ("Khalil Rountree", "The War Horse", []),
    ("Aleksandar Rakic", "Rocket", []),
    ("Dricus du Plessis", "Stillknocks", ["Dricus Du Plessis"]),
    ("Sean Strickland", "Tarzan", []),
    ("Israel Adesanya", "The Last Stylebender", ["Izzy Adesanya"]),
    ("Robert Whittaker", "The Reaper", []),
    ("Nassourdine Imavov", "The Sniper", []),
    ("Khamzat Chimaev", "Borz", []),
    ("Paulo Costa", "Borrachinha", []),
    ("Marvin Vettori", "The Italian Dream", []),
    ("Belal Muhammad", "Remember the Name", []),
    ("Leon Edwards", "Rocky", []),
    ("Kamaru Usman", "The Nigerian Nightmare", []),
    ("Shavkat Rakhmonov", "Nomad", []),
    ("Jack Della Maddalena", "JDM", []),
    ("Sean Brady", "", []),
    ("Ian Machado Garry", "The Future", ["Ian Garry"]),
    ("Colby Covington", "Chaos", []),
    ("Gilbert Burns", "Durinho", []),
    ("Islam Makhachev", "", []),
    ("Arman Tsarukyan", "Ahalkalakets", []),
    ("Charles Oliveira", "do Bronx", []),
    ("Justin Gaethje", "The Highlight", []),
    ("Dustin Poirier", "The Diamond", []),
    ("Max Holloway", "Blessed", []),
    ("Michael Chandler", "Iron", []),
    ("Conor McGregor", "The Notorious", []),
    ("Paddy Pimblett", "The Baddy", []),
    ("Dan Hooker", "The Hangman", []),
    ("Beneil Dariush", "Benny", []),
    ("Rafael Fiziev", "Ataman", []),
    ("Mateusz Gamrot", "Gamer", []),
    ("Ilia Topuria", "El Matador", []),
    ("Alexander Volkanovski", "The Great", ["Alex Volkanovski"]),
    ("Diego Lopes", "", []),
    ("Brian Ortega", "T-City", []),
    ("Yair Rodriguez", "El Pantera", []),
    ("Movsar Evloev", "", []),
    ("Arnold Allen", "Almighty", []),
    ("Josh Emmett", "The Fire Marshal", []),
    ("Merab Dvalishvili", "The Machine", []),
    ("Sean O'Malley", "Suga", ["Sean OMalley", "Suga Sean"]),
    ("Petr Yan", "No Mercy", []),
    ("Cory Sandhagen", "Sandman", []),
    ("Marlon Vera", "Chito", []),
    ("Umar Nurmagomedov", "", []),
    ("Deiveson Figueiredo", "Deus da Guerra", []),
    ("Henry Cejudo", "Triple C", []),
    ("Alexandre Pantoja", "The Cannibal", []),
    ("Brandon Moreno", "The Assassin Baby", []),
    ("Brandon Royval", "Raw Dawg", []),
    ("Kai Kara-France", "Don't Blink", []),
    ("Amir Albazi", "The Prince", []),
    ("Muhammad Mokaev", "The Punisher", []),
    ("Zhang Weili", "Magnum", ["Weili Zhang"]),
    ("Rose Namajunas", "Thug", []),
    ("Yan Xiaonan", "", ["Xiaonan Yan"]),
    ("Tatiana Suarez", "", []),
    ("Amanda Lemos", "Amandinha", []),
    ("Valentina Shevchenko", "Bullet", []),
    ("Alexa Grasso", "", []),
    ("Manon Fiorot", "The Beast", []),
    ("Erin Blanchfield", "Cold Blooded", []),
    ("Julianna Pena", "The Venezuelan Vixen", ["Julianna Peña"]),
    ("Raquel Pennington", "Rocky", []),
    ("Kayla Harrison", "", []),
    ("Amanda Nunes", "The Lioness", []),
    ("Ketlen Vieira", "Fenomeno", []),
    ("Mackenzie Dern", "", []),
    ("Jessica Andrade", "Bate Estaca", []),
    ("Maycee Barber", "The Future", []),
    ("Bo Nickal", "", []),
    ("Michael Page", "MVP", ["Michael Venom Page"]),
    ("Paul Craig", "Bearjew", []),
    ("Alex Caceres", "Bruce Leeroy", []),
    ("Bryce Mitchell", "Thug Nasty", []),
    ("Jean Silva", "Lord", []),
    ("Joaquin Buckley", "New Mansa", []),
    ("Stephen Thompson", "Wonderboy", []),
    ("Neil Magny", "The Haitian Sensation", []),
    ("Vicente Luque", "The Silent Assassin", []),
    ("Kevin Holland", "Trailblazer", []),
    ("Anthony Smith", "Lionheart", []),
    ("Dominick Reyes", "The Devastator", []),
    ("Volkan Oezdemir", "No Time", []),
    ("Marvin Vettori", "", []),
    ("Tai Tuivasa", "Bam Bam", []),
    ("Tom Nolan", "", []),
    ("Steve Erceg", "Astro Boy", []),
    ("Renato Moicano", "Money", []),
    ("Benoit Saint Denis", "God of War", []),
    ("Jalin Turner", "The Tarantula", []),
    ("Bobby Green", "King", []),
    ("Grant Dawson", "KGD", []),
    ("Chris Curtis", "The Action Man", []),
    ("Roman Dolidze", "", []),
    ("Caio Borralho", "The Natural", []),
    ("Anthony Hernandez", "Fluffy", []),
    ("Reinier de Ridder", "RDR", []),
    ("Marc-Andre Barriault", "PowerBar", []),
    ("Ateba Gautier", "", []),
    ("Waldo Cortes-Acosta", "Salsa Boy", []),
    ("Serghei Spivac", "Polar Bear", []),
    ("Marcin Tybura", "Tybur", []),
    ("Shara Magomedov", "Bullet", ["Shara Bullet"]),
    ("Mario Bautista", "", []),
    ("Payton Talbott", "", []),
    ("Aiemann Zahabi", "", []),
    ("Song Yadong", "Kung Fu Monkey", []),
    ("Marcus McGhee", "", []),
    ("Joshua Van", "", []),
    ("Tatsuro Taira", "", []),
    ("Charles Johnson", "InnerG", []),
    ("Virna Jandiroba", "Carcara", []),
    ("Gillian Robertson", "The Savage", []),
    ("Loopy Godinez", "", []),
    ("Karine Silva", "Killer", []),
    ("Natalia Silva", "", []),
    ("Chelsea Chandler", "Ms Fahrenheit", []),
    ("Norma Dumont", "The Immortal", []),
    ("Irene Aldana", "Robles", []),
]

# ---------------------------------------------------------- default settings
DEFAULT_SETTINGS: List[tuple] = [
    # key, value, type, (comment for humans)
    ("refresh_interval_minutes", "20", "int"),
    ("auto_collect_on_start", "0", "bool"),
    ("min_relevance", "0", "int"),
    ("default_sort", "Newest", "str"),
    ("default_filter", "ALL", "str"),
    ("theme", "dark", "str"),
    ("breaking_window_hours", "8", "int"),
    ("breaking_min_relevance", "70", "int"),
    ("important_min_relevance", "55", "int"),
    ("developing_window_hours", "48", "int"),
    ("trending_window_hours", "12", "int"),
    ("story_match_window_hours", "72", "int"),
    ("story_similarity_threshold", "0.42", "float"),
    ("story_title_similarity_threshold", "0.62", "float"),
    ("feed_max_stories", "60", "int"),
    ("article_fetch_full_text", "1", "bool"),
    ("collect_official_cards", "1", "bool"),
    ("article_fetch_limit_per_run", "12", "int"),
    ("x_enabled", "1", "bool"),
    ("x_search_enabled", "1", "bool"),
    ("x_timelines_enabled", "1", "bool"),
    ("ai_enabled", "1", "bool"),
    ("demo_data_loaded", "0", "bool"),
    ("last_collection_at", "", "str"),
]

# Watchlist starting points - all removable in the UI.
DEFAULT_WATCHLIST: List[tuple] = [
    ("topic", "title fight"),
    ("topic", "injury"),
    ("topic", "replacement"),
]
